### ISSUE TITLE
Improve Sortable component

### ISSUE THREAD

**Issue by apstanisic** [apstanisic/nadji-auto-web#8]
Currently it only works on this specific case. Maybe find some more concise alternative

**Comment by aleksandarstanisic** [comment]
Currently there is not viable replacement. Most of dnd and sortables don't have grid support. If grid support is not needed, we can use react-beautiful-dnd.

**Comment by aleksandarstanisic** [comment]
There is some weird bug that when devtools are open, it is trying to refetch images on every event.
